import streamlit as st
import torch, numpy as np
import json, pickle, os
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import pandas as pd

from src.preprocess import clean_text, Tokenizer, engineer_features, TEXT_COL, MAX_LEN
from src.model import BotDetector
from src.evaluate import get_all_metrics

# ── Config ────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="BotSentinel",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

MODEL_DIR  = "models"
DEVICE     = torch.device("cpu")
MODEL_READY = all(
    os.path.exists(f"{MODEL_DIR}/{f}")
    for f in ['best_model.pt','tokenizer.json','scaler.pkl',
              'meta_cols.json','history.json',
              'test_probs.npy','test_labels.npy']
)

# ── Loaders ───────────────────────────────────────────────────────────────────
@st.cache_resource
def load_artifacts():
    tok = Tokenizer.load(f"{MODEL_DIR}/tokenizer.json")
    with open(f"{MODEL_DIR}/scaler.pkl",    'rb') as f: scaler    = pickle.load(f)
    with open(f"{MODEL_DIR}/meta_cols.json"      ) as f: meta_cols = json.load(f)
    model = BotDetector(vocab_size=len(tok), embed_dim=128,
                        hidden_dim=64, meta_dim=len(meta_cols))
    model.load_state_dict(torch.load(f"{MODEL_DIR}/best_model.pt", map_location=DEVICE))
    model.eval()
    return tok, scaler, meta_cols, model

@st.cache_data
def load_history():
    with open(f"{MODEL_DIR}/history.json") as f: return json.load(f)

@st.cache_data
def load_test_results():
    return (np.load(f"{MODEL_DIR}/test_probs.npy"),
            np.load(f"{MODEL_DIR}/test_labels.npy"))

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("🛡️ BotSentinel")
    st.caption("Bot-Generated Comment Detector")
    st.divider()
    page = st.radio("Navigation", [
        "🏠 Overview",
        "📊 Dataset",
        "🧠 Architecture",
        "🔍 Live Detection",
        "📈 Results"
    ])
    st.divider()
    st.markdown("""
    **Model :** BiLSTM + Attention  
    **Dataset :** YouTube Spam Collection (UCI)  
    **Framework :** PyTorch  
    **Reference :** Airlangga (2024), MALCOM Journal
    """)
    if MODEL_READY:
        st.success("✅ Model loaded")
    else:
        st.error("⚠️ Model not trained yet")

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 1 — OVERVIEW
# ══════════════════════════════════════════════════════════════════════════════
if page == "🏠 Overview":
    st.title("🛡️ BotSentinel")
    st.subheader("Bot-Generated Comment Detection using Deep Learning")

    st.markdown("""
    Social media platforms face a massive problem: **bots** — automated accounts that
    flood comment sections with spam, misinformation, fake engagement, and malicious links.
    
    This project uses a **BiLSTM + Attention** deep learning model to automatically detect
    whether a comment was written by a **human** or generated by a **bot**.
    """)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("🎯 Task",     "Bot Comment Detection")
    col2.metric("📦 Dataset",  "YouTube Spam UCI")
    col3.metric("🧠 Model",    "BiLSTM + Attention")
    col4.metric("📄 Reference","Airlangga, 2024")

    st.divider()
    st.subheader("❓ Why does this matter?")
    c1, c2 = st.columns(2)
    with c1:
        st.error("🤖 Bots post thousands of spam comments per hour — impossible to moderate manually")
        st.error("📢 Bot comments spread fake links, phishing URLs, and scam promotions")
    with c2:
        st.warning("📉 Fake engagement distorts content recommendations and monetization")
        st.warning("🗳️ Coordinated bot campaigns manipulate public opinion at scale")

    st.divider()
    st.subheader("🔗 Bot Detection = Spam Comment Detection")
    st.info("""
    **Why are spam comments a bot detection problem?**  
    A single human cannot post thousands of identical comments across videos — 
    this is done by **automated bot accounts**. Detecting spam comments means 
    detecting bot-generated content. This is confirmed by the academic literature 
    *(Airlangga, 2024; Aravind & Mishra, 2023)*.
    """)

    st.subheader("⚙️ Project Pipeline")
    st.code("""
Input: YouTube comment text
    │
    ├── TEXT BRANCH
    │     raw comment
    │     → clean & tokenize (lowercase, remove URLs/mentions)
    │     → Embedding layer  (15k vocab, 128-dim vectors)
    │     → BiLSTM × 2 layers (hidden=64, bidirectional)
    │     → Attention layer   → 128-dim context vector
    │
    ├── FEATURE BRANCH (engineered from text)
    │     text length, word count, exclamation marks,
    │     caps ratio, URL presence, digit ratio ...
    │     → StandardScaler → Dense(32) → Dense(16)
    │
    └── FUSION
          Concatenate (128 + 16 = 144-dim)
          → Dense(64) → Dropout(0.3) → Sigmoid
          → 0 = Human comment  |  1 = Bot comment
    """, language="text")

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 2 — DATASET
# ══════════════════════════════════════════════════════════════════════════════
elif page == "📊 Dataset":
    st.title("📊 Dataset — YouTube Spam Collection (UCI)")
    st.markdown("""
    The **YouTube Spam Collection** dataset was created by Alberto et al. (2015) 
    and is hosted on the UCI Machine Learning Repository. It contains **real YouTube 
    comments** collected from 5 popular music videos, manually labeled as spam (bot) 
    or legitimate (human).
    """)

    st.subheader("Dataset composition")
    ds_data = {
        "Video":   ["Psy - Gangnam Style", "Katy Perry - Roar", "LMFAO - Party Rock",
                    "Eminem - Love the Way", "Shakira - She Wolf"],
        "Total":   [1000, 1000, 1000, 1000, 1000],
        "Bot/Spam":[355,  466,  236,  448,  526],
        "Human":   [645,  534,  764,  552,  474]
    }
    df_ds = pd.DataFrame(ds_data)

    c1, c2 = st.columns([2, 1])
    with c1:
        fig = go.Figure()
        fig.add_bar(name="Bot/Spam", x=df_ds["Video"], y=df_ds["Bot/Spam"],
                    marker_color="#D85A30")
        fig.add_bar(name="Human",    x=df_ds["Video"], y=df_ds["Human"],
                    marker_color="#1D9E75")
        fig.update_layout(barmode='group', title="Comments per video",
                          xaxis_tickangle=-15, height=350)
        st.plotly_chart(fig, use_container_width=True)
    with c2:
        fig2 = px.pie(values=[2031, 2969], names=["Bot/Spam","Human"],
                      color_discrete_sequence=["#D85A30","#1D9E75"],
                      title="Overall distribution")
        st.plotly_chart(fig2, use_container_width=True)

    st.divider()
    st.subheader("📌 Real comment examples")
    examples = pd.DataFrame({
        "Comment": [
            "Check out my channel for FREE subscribers!! Click NOW → bit.ly/xxx",
            "I love this song so much, brings back so many memories from 2012",
            "WIN AN IPHONE!! Just subscribe and comment done!! Limited time!!!",
            "The beat drop at 2:34 is absolutely insane, gives me chills every time",
            "Visit my profile link in bio for AMAZING deals you won't believe!!"
        ],
        "Label": ["🤖 Bot", "👤 Human", "🤖 Bot", "👤 Human", "🤖 Bot"]
    })
    st.dataframe(examples, use_container_width=True, hide_index=True)

    st.divider()
    st.subheader("🔧 Engineered features (metadata branch)")
    feat_df = pd.DataFrame({
        "Feature":     ["text_len","word_count","exclamation_count","question_count",
                        "caps_ratio","digit_ratio","url_count","has_url",
                        "repeated_chars","unique_word_ratio"],
        "Description": ["Total character length","Number of words",
                        "Number of ! marks","Number of ? marks",
                        "Ratio of uppercase letters","Ratio of digit characters",
                        "Number of URLs","Contains a URL (0/1)",
                        "Ratio of consecutively repeated characters",
                        "Ratio of unique words (low = repetitive = bot signal)"],
        "Bot signal":  ["Medium","Low","🔴 High","Low","🔴 High","Medium",
                        "🔴 High","🔴 High","Medium","🔴 High"]
    })
    st.dataframe(feat_df, use_container_width=True, hide_index=True)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 3 — ARCHITECTURE
# ══════════════════════════════════════════════════════════════════════════════
elif page == "🧠 Architecture":
    st.title("🧠 Model Architecture — BiLSTM + Attention")

    st.markdown("""
    Based on **Airlangga (2024)** who compared MLP, CNN, LSTM, BiLSTM, GRU and 
    Attention on this exact dataset, **BiLSTM with Attention** achieved the best 
    overall performance for YouTube spam comment detection.
    """)

    c1, c2 = st.columns(2)
    with c1:
        st.subheader("📝 Text Branch")
        st.markdown("""
        **1. Embedding layer**  
        Maps each word to a 128-dimensional dense vector.  
        Vocabulary: 15,000 most frequent tokens.

        **2. BiLSTM (2 layers)**  
        Reads the comment in both directions (left→right and right→left).  
        Hidden size = 64 per direction → 128 combined.  
        Captures context around every word.

        **3. Attention layer**  
        Learns which words are most suspicious.  
        Produces a weighted 128-dim context vector.  
        Makes the model interpretable — we can visualize what it focuses on.
        
        **4. BatchNorm**  
        Stabilizes gradients during training.
        """)
    with c2:
        st.subheader("🔧 Feature Branch")
        st.markdown("""
        **10 engineered features** extracted from the raw comment text:
        - Exclamation marks count
        - Caps ratio
        - URL presence
        - Unique word ratio
        - etc.

        These capture **structural bot patterns** that complement the text semantics.

        Processed through:  
        `Dense(32) → ReLU → Dropout → Dense(16) → ReLU`
        """)

    st.divider()
    st.subheader("🔀 Fusion & Output")
    st.markdown("""
    Text context (128-dim) **+** engineered features (16-dim) = **144-dim vector**  
    → `Dense(64)` → `ReLU` → `Dropout(0.3)` → `Dense(1)` → `Sigmoid`  
    → **Output: probability of being a bot comment (0.0 to 1.0)**
    """)

    st.divider()
    st.subheader("📋 Training configuration")
    c1,c2,c3,c4,c5 = st.columns(5)
    c1.metric("Optimizer",  "Adam")
    c2.metric("LR",         "1e-3")
    c3.metric("Loss",       "BCELoss")
    c4.metric("Batch size", "32")
    c5.metric("Early stop", "patience=5")

    st.divider()
    st.subheader("📚 Reference")
    st.info("""
    **Airlangga, G. (2024)**  
    *Spam Detection in YouTube Comments Using Deep Learning Models:  
    A Comparative Study of MLP, CNN, LSTM, BiLSTM, GRU, and Attention Mechanisms*  
    MALCOM: Indonesian Journal of Machine Learning and Computer Science, 4(4), 1533–1538.  
    https://doi.org/10.57152/malcom.v4i4.1671
    """)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 4 — LIVE DETECTION
# ══════════════════════════════════════════════════════════════════════════════
elif page == "🔍 Live Detection":
    st.title("🔍 Live Bot Comment Detection")
    st.markdown("Type or paste any YouTube comment — the model will classify it as **human** or **bot**.")

    if not MODEL_READY:
        st.error("⚠️ Model not trained yet. Run: `python -m src.train`")
        st.stop()

    tok, scaler, meta_cols, model = load_artifacts()

    # Quick examples
    st.subheader("💡 Try a quick example")
    c1, c2, c3 = st.columns(3)
    preset = ""
    if c1.button("🤖 Obvious Bot",   use_container_width=True):
        preset = "Check out my channel!! FREE subscribers click here NOW!! http://bit.ly/spam WIN IPHONE!!!"
    if c2.button("👤 Clear Human",   use_container_width=True):
        preset = "I remember listening to this song on repeat during summer vacation, absolute masterpiece."
    if c3.button("🤔 Ambiguous",     use_container_width=True):
        preset = "Great video! Follow me back for more amazing content every day! #subscribe #music"

    comment = st.text_area(
        "Comment to analyse",
        value=preset,
        placeholder="Paste a YouTube comment here...",
        height=110
    )

    if st.button("🔍 Analyse comment", type="primary", use_container_width=True):
        if not comment.strip():
            st.warning("Please enter a comment first.")
        else:
            # Preprocess
            cleaned  = clean_text(comment)
            text_ids = np.array([tok.encode(cleaned)], dtype=np.int64)

            row = pd.DataFrame({TEXT_COL: [comment], 'CLASS': [0]})
            row = engineer_features(row)
            meta_vec = np.array(
                [[row[c].iloc[0] if c in row.columns else 0 for c in meta_cols]],
                dtype=np.float32
            )
            meta_vec = scaler.transform(meta_vec)

            with torch.no_grad():
                prob, attn_w = model(torch.LongTensor(text_ids),
                                     torch.FloatTensor(meta_vec))
                prob = prob.item()

            st.divider()
            col_label, col_gauge = st.columns(2)

            # Verdict
            with col_label:
                is_bot = prob > 0.5
                label  = "🤖  BOT"   if is_bot else "👤  HUMAN"
                color  = "#D85A30"   if is_bot else "#1D9E75"
                conf   = prob        if is_bot else 1 - prob
                desc   = ("This comment shows strong signs of being **bot-generated**."
                          if is_bot else
                          "This comment appears to be written by a **real human**.")
                st.markdown(f"""
                <div style="background:{color}18;border:2px solid {color};
                border-radius:14px;padding:30px;text-align:center;margin-top:10px">
                    <div style="font-size:2.2rem;font-weight:700;color:{color}">{label}</div>
                    <div style="color:{color};font-size:1.1rem;margin:8px 0">
                        Confidence: <b>{conf:.1%}</b>
                    </div>
                    <div style="font-size:0.85rem;color:#555;margin-top:6px">
                        Bot probability: {prob:.4f}
                    </div>
                </div>
                """, unsafe_allow_html=True)
                st.markdown(f"\n{desc}")

            # Gauge
            with col_gauge:
                fig = go.Figure(go.Indicator(
                    mode="gauge+number",
                    value=round(prob * 100, 1),
                    title={"text": "Bot probability (%)"},
                    number={"suffix": "%"},
                    gauge={
                        "axis": {"range": [0, 100]},
                        "bar":  {"color": "#D85A30" if is_bot else "#1D9E75"},
                        "steps": [
                            {"range": [0,  50], "color": "#E8F8F0"},
                            {"range": [50, 100],"color": "#FDECEA"}
                        ],
                        "threshold": {
                            "line": {"color": "gray","width": 2},
                            "value": 50
                        }
                    }
                ))
                fig.update_layout(height=260, margin=dict(l=10,r=10,t=50,b=10))
                st.plotly_chart(fig, use_container_width=True)

            # Attention heatmap
            st.subheader("🔦 Attention map — what the model focused on")
            tokens  = cleaned.split()[:MAX_LEN]
            weights = attn_w[0].detach().numpy()[:len(tokens)]
            if weights.max() > weights.min():
                weights = (weights - weights.min()) / (weights.max() - weights.min())

            if tokens:
                fig_a = go.Figure(go.Bar(
                    x=tokens, y=weights,
                    marker_color=[f"rgba(216,90,48,{w:.2f})" for w in weights],
                    text=[f"{w:.2f}" for w in weights],
                    textposition="outside"
                ))
                fig_a.update_layout(
                    title="Attention weights per token (higher = more suspicious)",
                    xaxis_title="Token",
                    yaxis_title="Attention weight",
                    height=320,
                    yaxis=dict(range=[0, 1.15])
                )
                st.plotly_chart(fig_a, use_container_width=True)
                st.caption("🔴 Darker bars = words the model flagged as most bot-like")

            # Feature breakdown
            st.subheader("📊 Linguistic features detected")
            row2 = pd.DataFrame({TEXT_COL: [comment], 'CLASS': [0]})
            row2 = engineer_features(row2)
            feat_vals = {c: row2[c].iloc[0] for c in meta_cols if c in row2.columns}
            feat_df   = pd.DataFrame(list(feat_vals.items()),
                                     columns=["Feature","Value"])
            st.dataframe(feat_df, use_container_width=True, hide_index=True)

# ══════════════════════════════════════════════════════════════════════════════
# PAGE 5 — RESULTS
# ══════════════════════════════════════════════════════════════════════════════
elif page == "📈 Results":
    st.title("📈 Model Evaluation Results")

    if not MODEL_READY:
        st.error("⚠️ Train the model first: `python -m src.train`")
        st.stop()

    history              = load_history()
    te_probs, te_labels  = load_test_results()
    metrics              = get_all_metrics(te_labels, te_probs)
    rep                  = metrics['report']

    # KPI row
    c1,c2,c3,c4 = st.columns(4)
    c1.metric("✅ Accuracy",   f"{rep['accuracy']:.3f}")
    c2.metric("🤖 F1 — Bot",  f"{rep['Bot']['f1-score']:.3f}")
    c3.metric("📈 AUC-ROC",   f"{metrics['roc_auc']:.3f}")
    c4.metric("🎯 Precision",  f"{rep['Bot']['precision']:.3f}")

    st.divider()

    # Training curves
    st.subheader("📉 Training curves")
    epochs = list(range(1, len(history['train_loss'])+1))
    fig_c  = make_subplots(rows=1, cols=2, subplot_titles=("Loss","Accuracy"))
    for col, train_k, val_k in [
        (1,'train_loss','val_loss'), (2,'train_acc','val_acc')
    ]:
        fig_c.add_trace(go.Scatter(
            x=epochs, y=history[train_k], name="Train",
            line=dict(color="#1D9E75", width=2)), row=1, col=col)
        fig_c.add_trace(go.Scatter(
            x=epochs, y=history[val_k], name="Validation",
            line=dict(color="#D85A30", width=2, dash="dash"),
            showlegend=(col==1)), row=1, col=col)
    fig_c.update_layout(height=350, hovermode="x unified")
    st.plotly_chart(fig_c, use_container_width=True)

    # Confusion matrix + ROC
    st.subheader("📊 Confusion matrix & ROC curve")
    ca, cb = st.columns(2)
    with ca:
        fig_cm = px.imshow(
            metrics['cm'],
            labels=dict(x="Predicted", y="Actual"),
            x=["Human","Bot"], y=["Human","Bot"],
            text_auto=True,
            color_continuous_scale=["#E8F8F0","#0F6E56"],
            title="Confusion matrix"
        )
        fig_cm.update_layout(height=350)
        st.plotly_chart(fig_cm, use_container_width=True)
    with cb:
        fig_roc = go.Figure()
        fig_roc.add_trace(go.Scatter(
            x=metrics['fpr'], y=metrics['tpr'],
            name=f"ROC  AUC={metrics['roc_auc']:.3f}",
            line=dict(color="#1D9E75", width=2.5)
        ))
        fig_roc.add_trace(go.Scatter(
            x=[0,1], y=[0,1], name="Random",
            line=dict(dash="dash", color="gray")
        ))
        fig_roc.update_layout(
            title="ROC curve",
            xaxis_title="False Positive Rate",
            yaxis_title="True Positive Rate",
            height=350
        )
        st.plotly_chart(fig_roc, use_container_width=True)

    # Classification report table
    st.subheader("📋 Classification report")
    rep_df = pd.DataFrame({
        "Class":     ["Human","Bot","Macro avg"],
        "Precision": [rep['Human']['precision'], rep['Bot']['precision'],
                      rep['macro avg']['precision']],
        "Recall":    [rep['Human']['recall'],    rep['Bot']['recall'],
                      rep['macro avg']['recall']],
        "F1-score":  [rep['Human']['f1-score'],  rep['Bot']['f1-score'],
                      rep['macro avg']['f1-score']],
        "Support":   [int(rep['Human']['support']),
                      int(rep['Bot']['support']), ""]
    })
    st.dataframe(
        rep_df.style.format({"Precision":"{:.3f}","Recall":"{:.3f}","F1-score":"{:.3f}"}),
        use_container_width=True, hide_index=True
    )

    # Compare with literature
    st.divider()
    st.subheader("📚 Comparison with published results")
    lit_df = pd.DataFrame({
        "Model":    ["LSTM","GRU","CNN","BiLSTM","CNN-BiLSTM","🛡️ Our BiLSTM+Attention"],
        "Accuracy": [0.9413, 0.9541, 0.9464, 0.9694, 0.9643, rep['accuracy']],
        "Source":   ["Airlangga 2024","Airlangga 2024","Airlangga 2024",
                     "Airlangga 2024","Airlangga 2024","This project"]
    })
    fig_lit = px.bar(lit_df, x="Model", y="Accuracy", color="Source",
                     color_discrete_map={"Airlangga 2024":"#90CAF9",
                                         "This project":"#1D9E75"},
                     title="Accuracy comparison with literature",
                     text_auto='.3f')
    fig_lit.update_layout(height=380, yaxis=dict(range=[0.88, 1.0]))
    st.plotly_chart(fig_lit, use_container_width=True)